Repository rsuite/rsuite, pull requests merged in 2020-04, with the labels that each got.

#939 [docs]: Adjust the style of the navigation toggle button
  docs/components/Frame.tsx
  docs/components/SideNavbar/styles.less
  docs/components/TopLevelNav/TopLevelNav.tsx
  docs/components/TopLevelNav/styles.less
Labels: PR:docs

#955 Fixed an issue where the page crashed when clicking picker.
  docs/pages/components/form/index.tsx
Labels: PR:docs

#922 Fix input-picker height styles issue.
  src/InputPicker/test/InputPickerStylesSpec.js
  src/Picker/styles/mixin.less
Labels: PR:bugfix

#933 Fixed <DatePciker> onlyTime icon to clock icon.
  src/DatePicker/styles/common.less
  src/DatePicker/test/DatePickerStylesSpec.js
Labels: PR:bugfix

#930 docs: Update custom theme description
  docs/components/TopLevelNav/TopLevelNav.tsx
  docs/pages/guide/themes/en/index.md
  docs/pages/guide/themes/index.md
Labels: PR:docs

#929 Fixed modular issue for picker component.
  src/Picker/styles/themes/default.ts
Labels: PR:bugfix

#935 To optimize the placeholder active animation.
  src/Placeholder/styles/common.less
  src/styles/keyframes.less
  src/styles/themes/dark/variables.less
  src/styles/variables.less
Labels: PR:improve

#936 Added name and color to concurrently task.
  docs/package.json
Labels: PR:chore

#924 chore: Upgrade date-fns to v2
  package-lock.json
  package.json
  src/Calendar/Calendar.tsx
  src/Calendar/CalendarPanel.tsx
  src/Calendar/Header.tsx
  src/Calendar/MonthDropdown.tsx
  src/Calendar/MonthDropdownItem.tsx
  src/Calendar/TableRow.tsx
  src/Calendar/TimeDropdown.tsx
  src/Calendar/View.tsx
  src/Calendar/test/CalendarHeaderSpec.js
  src/Calendar/test/CalendarMonthDropdownItemSpec.js
  src/Calendar/test/CalendarPanelSpec.js
  src/Calendar/test/CalendarSpec.js
  src/Calendar/test/CalendarTableRowSpec.js
  src/DatePicker/DatePicker.tsx
  src/DatePicker/Toolbar.tsx
  src/DatePicker/test/DatePickerSpec.js
  src/DateRangePicker/Calendar/Calendar.tsx
  src/DateRangePicker/Calendar/TableRow.tsx
  src/DateRangePicker/Calendar/View.tsx
  src/DateRangePicker/DatePicker.tsx
  src/DateRangePicker/DateRangePicker.tsx
  src/DateRangePicker/Toolbar.tsx
  src/DateRangePicker/disabledDateUtils.ts
  src/DateRangePicker/test/DatePickerSpec.js
  src/DateRangePicker/test/DateRangePickerSpec.js
  src/DateRangePicker/test/disabledDateUtilsSpec.js
  src/DateRangePicker/utils.ts
  src/utils/disabledTime.ts
  src/utils/getMonthView.ts
  src/utils/test/getMonthViewSpec.js
  src/utils/timeUtils.ts
Labels: PR:chore

#912 Support container on Affix
  docs/pages/components/affix/container.md
  docs/pages/components/affix/en/container.md
  docs/pages/components/affix/en/index.md
  docs/pages/components/affix/index.md
  docs/pages/components/affix/index.tsx
  src/Affix/Affix.d.ts
  src/Affix/Affix.tsx
  src/Affix/test/AffixSpec.js
Labels: PR:feature

#927 feat(TagPicker): Support `tagProps` on TagPicker
  docs/pages/components/tag-picker/en/index.md
  docs/pages/components/tag-picker/index.md
  src/InputPicker/InputPicker.d.ts
  src/InputPicker/InputPicker.tsx
  src/TagPicker/TagPicker.d.ts
  src/TagPicker/test/TagPickerSpec.js
Labels: PR:feature

#938 feat(ProgressLine): Support `vertical` on ProgressLine
  docs/pages/components/progress/dynamic.md
  docs/pages/components/progress/en/dynamic.md
  docs/pages/components/progress/en/index.md
  docs/pages/components/progress/en/line-vertical.md
  docs/pages/components/progress/index.md
  docs/pages/components/progress/index.tsx
  docs/pages/components/progress/line-vertical.md
  docs/pages/components/progress/styles.less
  docs/pages/styles.less
  src/Progress/ProgressLine.d.ts
  src/Progress/ProgressLine.tsx
  src/Progress/styles/common.less
  src/Progress/test/ProgressLineSpec.js
  src/styles/keyframes.less
Labels: PR:feature

#932 feat(DatePicker): Support `showMeridian` on DatePicker
  docs/pages/components/date-picker/en/format-time-meridian.md
  docs/pages/components/date-picker/en/index.md
  docs/pages/components/date-picker/format-time-meridian.md
  docs/pages/components/date-picker/index.md
  docs/pages/components/date-picker/index.tsx
  src/Calendar/Calendar.tsx
  src/Calendar/Header.tsx
  src/Calendar/TimeDropdown.tsx
  src/Calendar/styles/common.less
  src/DatePicker/DatePicker.d.ts
  src/DatePicker/DatePicker.tsx
  src/DatePicker/test/DatePickerSpec.js
  src/styles/variables.less
Labels: PR:feature

#928 feat(Picker): Support `searchBy` on picker
  docs/pages/components/check-picker/en/index.md
  docs/pages/components/check-picker/index.md
  docs/pages/components/check-tree-picker/en/index.md
  docs/pages/components/check-tree-picker/index.md
  docs/pages/components/input-picker/en/index.md
  docs/pages/components/input-picker/index.md
  docs/pages/components/select-picker/en/index.md
  docs/pages/components/select-picker/index.md
  docs/pages/components/tag-picker/en/index.md
  docs/pages/components/tag-picker/index.md
  docs/pages/components/tree-picker/en/index.md
  docs/pages/components/tree-picker/index.md
  src/CheckPicker/CheckPicker.tsx
  src/CheckPicker/test/CheckPickerSpec.js
  src/CheckTreePicker/CheckTreePicker.tsx
  src/CheckTreePicker/test/CheckTreePickerSpec.js
  src/InputPicker/InputPicker.tsx
  src/InputPicker/test/InputPickerSpec.js
  src/Picker/utils.ts
  src/SelectPicker/SelectPicker.d.ts
  src/SelectPicker/SelectPicker.tsx
  src/SelectPicker/test/SelectPickerSpec.js
  src/Tree/TreeBase.d.ts
  src/TreePicker/TreePicker.tsx
  src/TreePicker/test/TreePickerSpec.js
  src/utils/treeUtils.ts
Labels: PR:feature

#918 feat(picker): Support `listProps` on `SelectPicker`,`CheckPicker`,`Ta…
  docs/pages/components/check-picker/en/index.md
  docs/pages/components/check-picker/index.md
  docs/pages/components/input-picker/en/index.md
  docs/pages/components/input-picker/index.md
  docs/pages/components/select-picker/en/index.md
  docs/pages/components/select-picker/index.md
  docs/pages/components/tag-picker/en/index.md
  docs/pages/components/tag-picker/index.md
  package-lock.json
  package.json
  src/Picker/DropdownMenu.tsx
  src/SelectPicker/SelectPicker.d.ts
Labels: PR:feature

#925 remove some deprecated tooltip properties
  docs/pages/components/tooltip/index.md
  src/Tooltip/Tooltip.d.ts
  src/Tooltip/Tooltip.tsx
  src/Tooltip/test/TooltipSpec.js
Labels: PR:bugfix, PR:docs

#917 Picker support size props at default.
  docs/pages/components/check-picker/en/size.md
  docs/pages/components/check-picker/size.md
  docs/pages/components/check-tree-picker/en/size.md
  docs/pages/components/check-tree-picker/size.md
  docs/pages/components/date-picker/en/size.md
  docs/pages/components/date-picker/size.md
  docs/pages/components/date-range-picker/en/size.md
  docs/pages/components/date-range-picker/size.md
  docs/pages/components/input-picker/en/size.md
  docs/pages/components/select-picker/en/size.md
  docs/pages/components/select-picker/size.md
  docs/pages/components/tag-picker/en/size.md
  docs/pages/components/tag-picker/size.md
  docs/pages/components/tree-picker/en/size.md
  docs/pages/components/tree-picker/size.md
  src/CheckPicker/test/CheckPickerSpec.js
  src/CheckTreePicker/test/CheckTreePickerSpec.js
  src/InputPicker/styles/common.less
  src/Picker/PickerToggle.tsx
  src/Picker/styles/common.less
  src/Picker/styles/mixin.less
  src/Picker/test/PickerToggleSpec.js
  src/SelectPicker/test/SelectPickerSpec.js
  src/SelectPicker/test/SelectPickerStylesSpec.js
  src/TreePicker/test/TreePickerStylesSpec.js
  src/styles/mixins/utilities.less
Labels: PR:bugfix

#978 Change picker-value-count badge padding .
  src/styles/variables.less
Labels: PR:bugfix

#980 Fixed the problem of abnormal display when <Timeline> has only one child.
  src/Timeline/styles/common.less
Labels: PR:bugfix

#985 Fixed #983
  docs/pages/components/dropdown/en/with-popover.md
  docs/pages/components/dropdown/with-popover.md
  src/Dropdown/styles/common.less
Labels: PR:bugfix

#982 feat(Timeline): Support `endless` on `<Timeline>`
  docs/pages/components/timeline/en/endless.md
  docs/pages/components/timeline/en/index.md
  docs/pages/components/timeline/endless.md
  docs/pages/components/timeline/index.md
  docs/pages/components/timeline/index.tsx
  src/Timeline/Timeline.d.ts
  src/Timeline/Timeline.tsx
  src/Timeline/styles/common.less
  src/Timeline/test/TimelineSpec.js
  src/styles/variables.less
Labels: PR:feature

#984 fix(Uploader): Fix typos
  CHANGELOG.md
  docs/pages/components/uploader/drag-and-drop.md
  docs/pages/components/uploader/en/drag-and-drop.md
  docs/pages/components/uploader/en/index.md
  docs/pages/components/uploader/index.md
  src/Uploader/UploadTrigger.tsx
  src/Uploader/Uploader.d.ts
  src/Uploader/Uploader.tsx
  src/Uploader/styles/common.less
  src/Uploader/test/UploaderSpec.js
Labels: PR:bugfix, breaking change

#981 add Rate component
  docs/pages/components/rate/basic.md
  docs/pages/components/rate/character.md
  docs/pages/components/rate/color.md
  docs/pages/components/rate/custom-character.md
  docs/pages/components/rate/disabled.md
  docs/pages/components/rate/en/basic.md
  docs/pages/components/rate/en/character.md
  docs/pages/components/rate/en/color.md
  docs/pages/components/rate/en/custom-character.md
  docs/pages/components/rate/en/disabled.md
  docs/pages/components/rate/en/half-select.md
  docs/pages/components/rate/en/index.md
  docs/pages/components/rate/en/size.md
  docs/pages/components/rate/en/vertical.md
  docs/pages/components/rate/half-select.md
  docs/pages/components/rate/index.md
  docs/pages/components/rate/index.tsx
  docs/pages/components/rate/size.md
  docs/pages/components/rate/vertical.md
  docs/utils/component.config.json
  src/Rate/Rate.d.ts
  src/Rate/Rate.tsx
  src/Rate/index.d.ts
  src/Rate/index.tsx
  src/Rate/styles/common.less
  src/Rate/styles/index.less
  src/Rate/styles/index.ts
  src/Rate/styles/themes/dark.less
  src/Rate/styles/themes/dark.ts
  src/Rate/styles/themes/default.less
  src/Rate/styles/themes/default.ts
  src/Rate/test/RateSpec.js
  src/Rate/utils.ts
  src/constants.ts
  src/index.d.ts
  src/index.tsx
  src/styles/themes/dark/index.less
  src/styles/themes/default/index.less
  src/styles/variables.less
Labels: PR:feature

#987 Tree Support Drag and Drop
  docs/package.json
  docs/pages/components/tree/basic.md
  docs/pages/components/tree/draggable.md
  docs/pages/components/tree/en/basic.md
  docs/pages/components/tree/en/draggable.md
  docs/pages/components/tree/en/index.md
  docs/pages/components/tree/en/virtualized.md
  docs/pages/components/tree/index.md
  docs/pages/components/tree/index.tsx
  docs/utils/useFetch.ts
  src/@types/common.d.ts
  src/CheckTreePicker/CheckTreeNode.tsx
  src/CheckTreePicker/CheckTreePicker.tsx
  src/Tree/TreeBase.d.ts
  src/TreePicker/TreeNode.tsx
  src/TreePicker/TreePicker.d.ts
  src/TreePicker/TreePicker.tsx
  src/TreePicker/styles/common.less
  src/TreePicker/test/TreePickerStylesSpec.js
  src/constants.ts
  src/utils/treeUtils.ts
Labels: PR:feature

#1007 fix(DropdownMenu): Fix the expanded state of the menu
  src/Dropdown/DropdownMenu.tsx
  src/Sidenav/test/SidenavSpec.js
Labels: PR:bugfix

#1008 fix(Table): Fix missing typescript type definitions
  src/Table/Table.d.ts
Labels: PR:bugfix
