Repository rsuite/rsuite, pull requests merged in 2020-05, with the labels that each got.

#1009 feat(Breadcrumb): Support `maxItems` and `onExpand` on `<Breadcrumb>`
  docs/pages/components/breadcrumb/en/index.md
  docs/pages/components/breadcrumb/en/max-items.md
  docs/pages/components/breadcrumb/index.md
  docs/pages/components/breadcrumb/index.tsx
  docs/pages/components/breadcrumb/max-items.md
  src/Breadcrumb/Breadcrumb.d.ts
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumb/BreadcrumbItem.tsx
  src/Breadcrumb/test/BreadcrumbSpec.js
Labels: PR:feature

#1039 Extract reset styles.
  docs/less/index.less
  docs/pages/components/css-reset/anchor.md
  docs/pages/components/css-reset/en/anchor.md
  docs/pages/components/css-reset/en/heading.md
  docs/pages/components/css-reset/en/index.md
  docs/pages/components/css-reset/en/list-dl.md
  docs/pages/components/css-reset/en/list-ol.md
  docs/pages/components/css-reset/en/list-ul.md
  docs/pages/components/css-reset/en/paragraph.md
  docs/pages/components/css-reset/heading.md
  docs/pages/components/css-reset/index.md
  docs/pages/components/css-reset/index.tsx
  docs/pages/components/css-reset/list-dl.md
  docs/pages/components/css-reset/list-ol.md
  docs/pages/components/css-reset/list-ul.md
  docs/pages/components/css-reset/paragraph.md
  docs/pages/components/timeline/styles.less
  docs/pages/guide/html-elements/en/index.md
  docs/pages/guide/html-elements/index.md
  docs/pages/guide/modularized/en/index.md
  docs/pages/guide/modularized/index.md
  docs/pages/guide/themes/en/index.md
  docs/pages/guide/themes/index.md
  docs/utils/component.config.json
  examples/with-babel-preset-rsuite/package-lock.json
  examples/with-babel-preset-rsuite/package.json
  examples/with-babel-preset-rsuite/webpack.config.js
  gulpfile.js
  src/Breadcrumb/styles/common.less
  src/Button/styles/common.less
  src/Button/styles/mixin.less
  src/Drawer/styles/common.less
  src/Dropdown/styles/common.less
  src/Modal/styles/common.less
  src/Nav/styles/common.less
  src/styles/constants.less
  src/styles/core.less
  src/styles/mixins/utilities.less
  src/styles/normalize.less
  src/styles/reset.less
  src/styles/scaffolding.less
Labels: PR:feature, PR:improve

#1072 Fix GitHub Actions status link in README
  README.md
Labels: PR:docs

#1080 Fix typo error in code example
  docs/pages/components/multi-cascader/en/disabled.md
Labels: PR:bugfix

#1075 Expand node when searching
  src/CheckTreePicker/CheckTreePicker.tsx
  src/TreePicker/TreePicker.tsx
  src/utils/treeUtils.ts
Labels: enhancement

#1081 Update Carousel.d.ts
  src/Carousel/Carousel.d.ts
Labels: PR:bugfix

#1068 Export component props from rsuite
  src/Breadcrumb/index.d.ts
  src/Dropdown/index.d.ts
  src/List/index.d.ts
  src/Nav/index.d.ts
  src/Placeholder/index.d.ts
  src/Progress/index.d.ts
  src/Table/TableColumnGroup.d.ts
  src/Table/index.d.ts
  src/Timeline/index.d.ts
  src/index.d.ts
Labels: PR:feature

#1079 fix slider-last-mark content not justify with dot
  src/Slider/styles/common.less
Labels: PR:bugfix

#1078 chore(commitlint): lint commit message
  .huskyrc
  commitlint.config.js
  package-lock.json
  package.json
Labels: PR:chore

#1082 fix(slider): fix Slider drag handle error
  src/Slider/Handle.tsx
Labels: PR:bugfix
