Repository rsuite/rsuite, pull requests merged in 2020-06, with the labels that each got.

#1101 docs(example): add example of Reason app
  examples/with-reason-webpack/.gitignore
  examples/with-reason-webpack/README.md
  examples/with-reason-webpack/bsconfig.json
  examples/with-reason-webpack/package.json
  examples/with-reason-webpack/src/App.re
  examples/with-reason-webpack/src/Styles.re
  examples/with-reason-webpack/src/index.html
  examples/with-reason-webpack/src/index.re
  examples/with-reason-webpack/webpack.config.js
  examples/with-reason-webpack/yarn.lock
Labels: PR:example

#1094 fix(dropdown): fix incorrect Dropdown caret position
  docs/pages/components/dropdown/en/size.md
  docs/pages/components/dropdown/index.tsx
  docs/pages/components/dropdown/size.md
  package.json
  src/Button/styles/mixin.less
  src/Dropdown/styles/common.less
  src/Dropdown/styles/mixin.less
  src/Form/styles/mixin.less
  src/Picker/styles/mixin.less
  src/TreePicker/styles/common.less
  src/styles/mixins/palette.less
  src/styles/mixins/tiny-color.less
  src/styles/normalize.less
Labels: PR:bugfix

#1087 fix(buttongroup): fixed Button componentClass not work with ButtonGroup
  src/ButtonGroup/ButtonGroup.tsx
  src/ButtonGroup/test/ButtonGroupSpec.js
Labels: PR:bugfix

#1092 fix(picker): remove redundant ripple elements in PickerToggle
  src/Button/Button.d.ts
  src/Button/Button.tsx
  src/Picker/DefaultToggleButton.tsx
  src/Picker/PickerToggle.tsx
Labels: PR:bugfix

#1090 fix(sidenav): fixed display issue when sidenav was collapsed
  src/Dropdown/Dropdown.d.ts
  src/Dropdown/Dropdown.tsx
  src/Nav/Nav.tsx
  src/Nav/NavItem.tsx
  src/Whisper/index.tsx
  src/utils/appendTooltip.tsx
Labels: PR:bugfix

#1095 Fix CheckPicker disabledItemValues any[][]
  src/@types/common.d.ts
Labels: PR:bugfix

#1096 fix(inputpicker): fix InputNumber will not trigger onChange when input
  src/InputNumber/InputNumber.tsx
  src/InputNumber/test/InputNumberSpec.js
Labels: PR:bugfix

#1100 fix(steps): fixed the description of <Steps> will break layout
  docs/pages/components/steps/description.md
  docs/pages/components/steps/en/description.md
  src/Steps/StepItem.tsx
  src/Steps/styles/common.less
Labels: PR:bugfix

#1098 Split FormControlAccepterProps from FormControlProps
  src/FormControl/FormControl.d.ts
Labels: PR:improve
