Repository rsuite/rsuite, pull requests merged in 2020-01, with the labels that each got.

#752 Supported drag and drop for <Uploader>
  src/Uploader/UploadTrigger.tsx
  src/Uploader/Uploader.d.ts
  src/Uploader/Uploader.tsx
  src/Uploader/styles/common.less
  src/Uploader/test/UploaderSpec.js
  src/styles/themes/dark/variables.less
  src/styles/variables.less
Labels: PR:feature

#755 Added option `image` to the `graph` property of Placeholder
  src/Placeholder/PlaceholderParagraph.d.ts
  src/Placeholder/PlaceholderParagraph.tsx
  src/Placeholder/styles/common.less
  src/Placeholder/test/PlaceholderParagraphSpec.js
  src/styles/themes/dark/variables.less
  src/styles/themes/default/variables.less
  src/styles/variables.less
Labels: PR:feature

#802 Added support for `parentSelectable` on `<Cascader>`
  src/Cascader/Cascader.d.ts
  src/Cascader/Cascader.tsx
  src/Cascader/DropdownMenu.tsx
  src/Cascader/test/CascaderSpec.js
  src/MultiCascader/DropdownMenu.tsx
  src/MultiCascader/MultiCascader.d.ts
  src/MultiCascader/MultiCascader.tsx
  src/Picker/DropdownMenu.tsx
Labels: PR:feature

#796 Fix CheckTreePicker and TreePicker Bug
  src/CheckTreePicker/CheckTreePicker.tsx
  src/TreePicker/TreePicker.tsx
Labels: PR:bugfix

#795 Fix #794
  src/Grid/styles/grid-framework.less
  src/styles/variables.less
Labels: PR:bugfix

#803 Fix #777
  src/Modal/Modal.tsx
  src/Modal/ModalDialog.tsx
Labels: PR:bugfix

#799 Create ru_RU.ts
  src/IntlProvider/locales/ru_RU.ts
Labels: PR:Improve

#804 Chore:specify explicit propTypes to avoid hidden dangers of higher-or…
  src/Cascader/Cascader.tsx
  src/Cascader/DropdownMenu.tsx
  src/CheckPicker/CheckPicker.tsx
  src/InputPicker/InputPicker.tsx
  src/MultiCascader/DropdownMenu.tsx
  src/MultiCascader/MultiCascader.tsx
  src/Picker/DropdownMenu.tsx
  src/SelectPicker/SelectPicker.tsx
Labels: PR:chore

#806 Enhance Tooltip and Popover to support HTML attributes
  src/Popover/Popover.tsx
  src/Popover/test/PopoverSpec.js
  src/Tooltip/Tooltip.tsx
  src/Tooltip/test/TooltipSpec.js
  src/Whisper/Whisper.tsx
Labels: PR:Improve

#810 Fix toggle text/icon font size
  src/Toggle/styles/common.less
  src/Toggle/styles/mixin.less
  src/styles/variables.less
Labels: PR:bugfix

#812 Fixed: #809
  src/List/styles/common.less
  src/styles/variables.less
Labels: PR:bugfix

#817 Fix vertical alignment of xs datepicker icon
  src/Picker/styles/mixin.less
Labels: PR:bugfix

#822 Update ts type definition for Animation
  src/Animation/index.d.ts
Labels: PR:bugfix

#830 Fixed "script-src" content security policy (CSP) failure
  src/utils/prefix.ts
Labels: PR:bugfix
